version: '3'

services:

  uexkb-db:
      build:
        context: .
        dockerfile: db.dockerfile
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=testRoot
        - MYSQL_DATABASE=yourdatabase
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "3306:3306"

  uexkb-web:
    #image: php:5.6-apache
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - uexkb-db:uexkb-db