version: '3'

services:

  db:
      image: mysql:5.6
      volumes:
        - ./backups/data:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=testRoot
        - MYSQL_DATABASE=yourdatabase
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "3306:3306"

  web:
    build:
      context: .
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - db:db
